In [33]:
import numpy
import numpy as np

item_w = 3
n_items_in_bank = 100
n_users = 1000
av_pass_rate = 0.5
items_are_conj = True

def sigmoid(z):
    return 1/(1 + np.exp(-z)) 

def inv_sigmoid(p):
    return -np.log((1/p)-1)

ptest=sigmoid(3)
ztest=inv_sigmoid(ptest)
assert np.isclose(0.95257, ptest)
assert np.isclose(3, ztest)

print("..." , inv_sigmoid(0.5))

av_KCp = av_pass_rate**(1/item_w) if items_are_conj else 1/item_w
av_KCs = inv_sigmoid(av_KCp)
print(av_KCs)

users = np.random.normal(size=(n_users, item_w), loc=av_KCs, scale=0.5)
items = np.random.normal(size=(n_items_in_bank, item_w), loc=0, scale=0.5)
print(users)
print(items)

ps = []
for s in users:
    for q in items:
        logit_differences = s-q
        if items_are_conj:
            p = np.prod(sigmoid(logit_differences))
        else:
            p = sigmoid(np.sum(logit_differences))
        ps.append(p)
print(numpy.mean(ps), numpy.median(ps))

... -0.0
1.347377348329385
[[0.80246794 1.53257772 1.51404705]
 [1.22787511 1.16894637 1.11311453]
 [1.30290623 0.86621061 1.31628019]
 ...
 [1.35928867 0.3359651  0.39361326]
 [0.75158513 0.82554019 1.74990626]
 [0.88786808 1.20293957 0.52760726]]
[[ 4.38349848e-01  5.29929850e-01  2.16913026e-01]
 [ 4.13758240e-01  8.13724525e-01  5.51618456e-01]
 [ 8.08277412e-01  2.03151183e-01 -5.01659325e-01]
 [-7.31602779e-03 -2.90829718e-01 -9.68755434e-02]
 [-3.07339530e-01 -1.68558311e-01  9.64710591e-02]
 [-5.00424823e-01 -6.95197621e-01 -4.09038196e-01]
 [ 4.56278376e-01 -2.51177212e-01  1.26596524e-01]
 [ 6.00417092e-01  5.28894464e-01  1.76878718e-01]
 [ 1.49107331e+00  7.15720520e-01  3.69555664e-01]
 [ 1.32964286e-02 -4.97100053e-01  4.54528371e-01]
 [-5.08979573e-01 -6.77600779e-01 -3.95715060e-01]
 [ 6.11886504e-01  6.15798489e-01 -7.85916305e-02]
 [-9.44688055e-01 -1.43917986e-01  4.87062373e-01]
 [ 4.89384219e-01  3.28500263e-01  3.70047764e-01]
 [-6.06284959e-01  9.92530252e-01 -8.